import fs from "fs";
import readline from "readline";
import { GoogleGenerativeAI } from "@google/generative-ai";
import dotenv from "dotenv";

dotenv.config();

const apiKey = process.env.GEMINI_API_KEY;
if (!apiKey) {
  console.error("ERROR: GEMINI_API_KEY not found in .env file!");
  process.exit(1);
}

const genAI = new GoogleGenerativeAI(apiKey);
const model = genAI.getGenerativeModel({ model: "gemini-2.0-flash" });

/**
 * Deep Behavioral Analysis System
 * Discovers hidden patterns, causal rules, and behavioral laws
 */

class BehavioralAnalyzer {
  constructor(logFileName) {
    this.logFileName = logFileName;
    this.role = logFileName.replace('_daily', '');
    this.logFile = `logs/${logFileName}.jsonl`;
    this.reportFile = `analysis/${logFileName}_analysis.md`;
    this.events = [];
  }

  loadEvents() {
    const data = fs.readFileSync(this.logFile, 'utf-8');
    const lines = data.split('\n').filter(l => l.trim());
    this.events = lines.map(l => JSON.parse(l));
    console.log(`📖 Loaded ${this.events.length} events for role: ${this.role}`);
  }

  async analyzePatterns() {
    /**
     * Send all events to Gemini for deep pattern analysis
     */
    const eventSummary = this.events.map((e, i) => 
      `[${i+1}] ${e.time} | ${e.action} | ${e.detail} → ${e.outcome}${e.error ? ` [ERROR: ${e.error}]` : ''}`
    ).join('\n');

    const systemPrompt = `You are a behavioral scientist analyzing human daily activity logs.

Your task:
1. Identify OBSERVED PATTERNS: Exact sequences and timing of events that repeatedly occur
2. Detect EMERGENT BEHAVIORS: System-level patterns arising from combinations of actions
3. Formulate HYPOTHESIZED RULES: If [Condition A] + [Condition B] occur → [Outcome C] happens
4. Suggest SOLUTIONS: Specific, actionable preventive actions based on detected rules
5. Note UNCERTAINTIES: Data gaps, unclear causalities, need for more information

CRITICAL CONSTRAINTS:
- Do NOT assume intent or motivation
- Do NOT moralize or judge
- Act as objective scientist observing patterns ONLY
- Focus on causal chains: which event combinations trigger what outcomes
- Identify "invisible laws" that govern behavior naturally

Output format:
# Behavioral Analysis: [ROLE]

## 1. Observed Patterns
(Describe exact sequences, timing, error flags)

## 2. Possible Emergent Behaviors
(Group-level patterns, cascade effects)

## 3. Hypothesized Rules
Rule Name: If [A] + [B] → [C]
Mechanism: (explain why this causal link exists)

## 4. Suggested Solutions
(Preventive or corrective actions per rule)

## 5. Uncertainty / Ambiguities
(What's unclear or needs more data)`;

    const userPrompt = `Analyze this daily activity log for a ${this.role}:

${eventSummary}

Identify hidden behavioral patterns, causal rules, and emergent phenomena. Focus on discovering the invisible laws that govern this person's day.`;

    console.log(`\n Sending to Gemini for deep analysis...`);
    
    try {
      const response = await model.generateContent({
        contents: [
          {
            role: "user",
            parts: [{ text: userPrompt }],
          },
        ],
        systemInstruction: systemPrompt,
      });

      const analysis = response.response.text();
      return analysis;
    } catch (error) {
      console.error(`❌ Analysis error:`, error.message);
      return null;
    }
  }

  async generateReport(analysis) {
    /**
     * Write structured analysis report
     */
    if (!fs.existsSync('analysis')) {
      fs.mkdirSync('analysis', { recursive: true });
    }

    const timestamp = new Date().toISOString();
    const report = `# Behavioral Analysis Report: ${this.role.toUpperCase()}

**Generated:** ${timestamp}  
**Events Analyzed:** ${this.events.length}  
**Methodology:** Gemini Deep Behavioral Pattern Discovery

---

${analysis}

---

**Report generated by Behavioral Analysis System**`;

    fs.writeFileSync(this.reportFile, report, 'utf-8');
    console.log(` Report saved: ${this.reportFile}`);
  }

  async run() {
    try {
      this.loadEvents();
      const analysis = await this.analyzePatterns();
      if (analysis) {
        await this.generateReport(analysis);
      }
    } catch (error) {
      console.error(`Error analyzing ${this.role}:`, error.message);
    }
  }
}

// ============================================================================
// Main execution
// ============================================================================
async function main() {
  console.log("=".repeat(70));
  console.log("🔬 BEHAVIORAL PATTERN DISCOVERY SYSTEM");
  console.log("=".repeat(70));
  console.log("Analyzing hidden laws in human daily behavior...\n");

  const roles = [
    'developer_daily',
    'office_employee_daily', 
    'student_daily',
    'driver_daily'
  ];

  for (const roleFile of roles) {
    const role = roleFile.replace('_daily', '');
    console.log(`\n${"=".repeat(70)}`);
    console.log(`Analyzing: ${role.toUpperCase()}`);
    console.log("=".repeat(70));
    
    const analyzer = new BehavioralAnalyzer(roleFile);
    await analyzer.run();
    
    // Rate limiting: wait between API calls
    await new Promise(r => setTimeout(r, 2000));
  }

  console.log(`\n${"=".repeat(70)}`);
  console.log(" ALL ANALYSES COMPLETE");
  console.log("=".repeat(70));
  console.log("\nGenerated reports:");
  console.log("  - analysis/developer_daily_analysis.md");
  console.log("  - analysis/office_employee_daily_analysis.md");
  console.log("  - analysis/student_daily_analysis.md");
  console.log("  - analysis/driver_daily_analysis.md");
}

main().catch(console.error);
